---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: c77a0d9be97b39bbb1a01f2dd7302cb99571808c
    app.quarkus.io/build-timestamp: 2023-02-03 - 09:21:15 +0000
  labels:
    app.kubernetes.io/name: acme
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: acme
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: acme
