---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 24b419fd0ed87ea4bff7e4adae3f4382244ad4df
    app.quarkus.io/build-timestamp: 2023-02-06 - 14:21:52 +0000
  labels:
    app.kubernetes.io/name: acme
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: acme
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: acme
