---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: d6db5b0ce4401e9b0cca56ac6e113a993d488375
    app.quarkus.io/build-timestamp: 2023-02-06 - 12:18:29 +0000
  labels:
    app.kubernetes.io/name: acme
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: acme
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: acme
