---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 24b419fd0ed87ea4bff7e4adae3f4382244ad4df
    app.quarkus.io/build-timestamp: 2023-02-06 - 14:21:52 +0000
  labels:
    app.kubernetes.io/name: acme
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: acme
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: acme
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 24b419fd0ed87ea4bff7e4adae3f4382244ad4df
        app.quarkus.io/build-timestamp: 2023-02-06 - 14:21:52 +0000
      labels:
        app.kubernetes.io/name: acme
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: {{ .Values.app.image }}
          imagePullPolicy: Always
          name: acme
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
