---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 0c8e63b3566e5ac8515134906c3bfa2c245141b6
    app.quarkus.io/build-timestamp: 2023-02-06 - 14:51:28 +0000
  labels:
    app.kubernetes.io/version: {{ .Values.app.labelVersion }}
    app.kubernetes.io/name: acme
  name: acme
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: {{ .Values.app.labelVersion }}
      app.kubernetes.io/name: acme
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 0c8e63b3566e5ac8515134906c3bfa2c245141b6
        app.quarkus.io/build-timestamp: 2023-02-06 - 14:51:28 +0000
      labels:
        app.kubernetes.io/version: {{ .Values.app.labelVersion }}
        app.kubernetes.io/name: acme
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: {{ .Values.app.image }}
          imagePullPolicy: {{ .Values.app.imagePullPolicy }}
          name: acme
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
