---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 0c8e63b3566e5ac8515134906c3bfa2c245141b6
    app.quarkus.io/build-timestamp: 2023-02-06 - 14:51:28 +0000
  labels:
    app.kubernetes.io/name: acme
    app.kubernetes.io/version: {{ .Values.app.labelVersion }}
  name: acme
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: acme
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: {{ .Values.app.serviceType }}
